[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
syn = "2.0.77"
quote = "1.0.37"
easy_config = {path = "../../easy_config"}
